//! Chrome-configured BoringSSL TLS context (Tier-1 "real Chrome ClientHello" layer).
//!
//! Design principle (DonSeTch-inspired, clean-room): the ClientHello is generated by
//! Chrome's own TLS machinery — BoringSSL — with Chrome's native behaviors enabled
//! (GREASE, extension permutation, ECH-GREASE, ALPS, SCT, OCSP, brotli cert-compression).
//! The pinned Chrome posture lives in `src/antibot/python/fingerprints.py` as a data
//! table; this module applies it. When Chrome's posture shifts, update the table —
//! not this library — except where BoringSSL requires literal values (kept minimal).
//!
//! Honest API-gap notes live in the repo-root BUILD_NOTES.md.

use std::io::{Read, Write};
use std::net::TcpStream;

use boring::error::ErrorStack;
use boring::ssl::{
    CertificateCompressionAlgorithm, CertificateCompressor, ConnectConfiguration, SslConnector,
    SslMethod, SslStream, SslVersion,
};
use boring_sys as ffi;
use foreign_types::ForeignTypeRef;
use serde_json::{json, Value};

// ---------------------------------------------------------------------------
// Pinned Chrome posture (mirror of src/antibot/python/fingerprints.py).
// Keep in sync; fingerprints.py is the config-of-record.
// ---------------------------------------------------------------------------

/// Chrome TLS 1.2 cipher list, in Chrome's offer order (OpenSSL names).
pub const CHROME_CIPHERS_TLS12: &str = "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:\
     ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:\
     ECDHE-RSA-CHACHA20-POLY1305:ECDHE-RSA-AES128-SHA:ECDHE-RSA-AES256-SHA:AES128-GCM-SHA256:\
     AES256-GCM-SHA384:AES128-SHA:AES256-SHA";

/// Chrome TLS 1.3 cipher suites, in Chrome's offer order.
pub const CHROME_CIPHERS_TLS13: &str =
    "TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256";

/// Chrome key-share groups (hybrid post-quantum first, as Chrome ships).
pub const CHROME_CURVES: &str = "X25519MLKEM768:X25519:P-256:P-384";

/// Chrome signature algorithms (TLSEXT_signature_algorithm codes), offer order.
pub const CHROME_SIG_ALGS: &[u16] = &[
    0x0904, // mldsa44 (Chrome 151 hybrid PQ first)
    0x0905, // mldsa65
    0x0906, // mldsa87
    0x0403, // ecdsa_secp256r1_sha256
    0x0804, // rsa_pss_rsae_sha256
    0x0401, // rsa_pkcs1_sha256
    0x0503, // ecdsa_secp384r1_sha384
    0x0805, // rsa_pss_rsae_sha384
    0x0501, // rsa_pkcs1_sha384
    0x0806, // rsa_pss_rsae_sha512
    0x0601, // rsa_pkcs1_sha512
];

/// Chrome ALPN list in offer order.
pub const CHROME_ALPN: &[&str] = &["h2", "http/1.1"];

/// Chrome HTTP/2 SETTINGS sent inside the ALPS extension (key -> value).
pub const CHROME_ALPS_H2_SETTINGS: &[(u16, u32)] = &[
    (1, 65536),   // HEADER_TABLE_SIZE
    (2, 0),       // ENABLE_PUSH
    (4, 6291456), // INITIAL_WINDOW_SIZE
    (6, 262_144), // MAX_HEADER_LIST_SIZE
];

fn alpn_wire(protocols: &[&str]) -> Vec<u8> {
    let mut out = Vec::new();
    for p in protocols {
        out.push(p.len() as u8);
        out.extend_from_slice(p.as_bytes());
    }
    out
}

/// Wire bytes of the ALPS application-settings payload for h2 (16-bit key,
/// 32-bit value big-endian, same encoding as a SETTINGS frame payload).
fn alps_h2_settings_wire() -> Vec<u8> {
    let mut out = Vec::new();
    for (k, v) in CHROME_ALPS_H2_SETTINGS {
        out.extend_from_slice(&k.to_be_bytes());
        out.extend_from_slice(&v.to_be_bytes());
    }
    out
}

// ---------------------------------------------------------------------------
// Brotli certificate compression (Chrome only offers brotli)
// ---------------------------------------------------------------------------

struct BrotliCertCompressor;

impl CertificateCompressor for BrotliCertCompressor {
    const ALGORITHM: CertificateCompressionAlgorithm = CertificateCompressionAlgorithm::BROTLI;
    const CAN_COMPRESS: bool = true;
    const CAN_DECOMPRESS: bool = true;

    fn compress<W: Write>(&self, input: &[u8], output: &mut W) -> std::io::Result<()> {
        let mut w = brotli::CompressorWriter::new(output, 4096, 11, 22);
        w.write_all(input)?;
        w.flush()
    }

    fn decompress<W: Write>(&self, input: &[u8], output: &mut W) -> std::io::Result<()> {
        brotli::BrotliDecompress(&mut std::io::Cursor::new(input), output)
    }
}

// ---------------------------------------------------------------------------
// Chrome-configured SslContext
// ---------------------------------------------------------------------------

/// Build a BoringSSL `SslContext` configured the way Chrome configures its own.
///
/// Flags that BoringSSL only exposes per-connection (ECH-GREASE, ALPS) are applied
/// by [`apply_per_connection_chrome_toggles`] on every `ConnectConfiguration` the
/// transport creates; `tls_config_json()` reports the effective posture.
pub fn build_chrome_context() -> Result<SslConnector, ErrorStack> {
    let mut b = SslConnector::builder(SslMethod::tls())?;

    // TLS 1.3 + 1.2 only (Chrome dropped 1.1 and below).
    b.set_min_proto_version(Some(SslVersion::TLS1_2))?;
    b.set_max_proto_version(Some(SslVersion::TLS1_3))?;

    // Chrome cipher list (offer order matters for JA4's cipher digest).
    // NOTE: BoringSSL has no set_ciphersuites — TLS 1.3 suites are always
    // offered in BoringSSL's fixed order (AES128-GCM, AES256-GCM, CHACHA20),
    // which happens to match Chrome's TLS 1.3 order.
    b.set_cipher_list(CHROME_CIPHERS_TLS12)?;

    // Key-share groups.
    if b.set_curves_list(CHROME_CURVES).is_err() {
        // Older BoringSSL without hybrid ML-KEM: fall back to the classic set.
        b.set_curves_list("X25519:P-256:P-384")?;
    }

    // Signature algorithms (via raw FFI; boring 4.22 has no safe wrapper).
    // Chrome 151's list leads with hybrid PQ (ML-DSA) entries; a BoringSSL
    // build without ML-DSA support rejects them outright, so fall back to the
    // classic (non-PQ) prefix on failure. Documented in BUILD_NOTES.md.
    let sigs: Vec<u16> = CHROME_SIG_ALGS.to_vec();
    let classic: Vec<u16> = sigs
        .iter()
        .copied()
        .filter(|s| !matches!(s, 0x0904 | 0x0905 | 0x0906))
        .collect();
    unsafe {
        let ok = ffi::SSL_CTX_set_signing_algorithm_prefs(b.as_ptr(), sigs.as_ptr(), sigs.len())
            == 1
            || ffi::SSL_CTX_set_signing_algorithm_prefs(
                b.as_ptr(),
                classic.as_ptr(),
                classic.len(),
            ) == 1;
        if !ok {
            return Err(ErrorStack::get());
        }
    }

    // Chrome's native ClientHello behaviors.
    b.set_grease_enabled(true); // RFC 8701 GREASE values
    b.set_permute_extensions(true); // Chrome's extension-order randomization
    b.enable_signed_cert_timestamps(); // SCT (status_request + signed_certificate_timestamp)
    b.enable_ocsp_stapling(); // status_request
    b.add_certificate_compression_algorithm(BrotliCertCompressor)?; // compress_certificate: brotli

    // ALPN [h2, http/1.1] in offer order.
    b.set_alpn_protos(&alpn_wire(CHROME_ALPN))?;

    Ok(b.build())
}

/// Apply Chrome's per-connection toggles (boring has no context-level APIs for
/// these — see BUILD_NOTES.md): ECH-GREASE and ALPS (h2 application settings).
fn apply_per_connection_chrome_toggles(config: &ConnectConfiguration) -> Result<(), String> {
    // ECH-GREASE: boring exposes SSL_set_enable_ech_grease via SslRef; a
    // ConnectConfiguration derefs to SslRef.
    config.set_enable_ech_grease(true);

    // ALPS: SSL_add_application_settings(ssl, proto, proto_len, settings, settings_len).
    // Chrome registers ALPS for h2 with its exact SETTINGS values.
    let proto = b"h2";
    let settings = alps_h2_settings_wire();
    // SAFETY: `config` derefs to a valid SslRef whose as_ptr() is a live SSL*
    // for the lifetime of the connection setup; both buffers outlive the call.
    let rc = unsafe {
        ffi::SSL_add_application_settings(
            config.as_ptr() as *mut _,
            proto.as_ptr(),
            proto.len(),
            settings.as_ptr(),
            settings.len(),
        )
    };
    if rc != 1 {
        return Err("SSL_add_application_settings failed".into());
    }
    Ok(())
}

/// Effective Chrome posture of the engine, as JSON (for config-level tests).
///
/// `ech_grease` and `alps` are applied per connection (BoringSSL exposes no
/// context-level toggles); the values here reflect what `probe_fingerprint`
/// actually applies to every connection it makes.
pub fn tls_config_json() -> String {
    let cfg = json!({
        "grease_enabled": true,            // SSL_CTX_set_grease_enabled
        "extension_permutation": true,     // SSL_CTX_set_permute_extensions
        "ech_grease": true,                // per-SSL (SSL_set_enable_ech_grease) — see BUILD_NOTES.md
        "alps": true,                      // per-SSL (SSL_add_application_settings, h2) — see BUILD_NOTES.md
        "brotli_cert_compression": true,   // SSL_CTX_add_cert_compression_alg (brotli)
        "sct": true,                       // SSL_CTX_enable_signed_cert_timestamps
        "ocsp_stapling": true,             // SSL_CTX_enable_ocsp_stapling
        "alpn": CHROME_ALPN,
        "tls_min": "TLS1.2",
        "tls_max": "TLS1.3",
        "ciphers_tls12_count": CHROME_CIPHERS_TLS12.split(':').count(),
        "ciphers_tls13_count": CHROME_CIPHERS_TLS13.split(':').count(),
        "sig_algs_count": CHROME_SIG_ALGS.len(),
        "curves": CHROME_CURVES,
        "alps_h2_settings": CHROME_ALPS_H2_SETTINGS
            .iter()
            .map(|(k, v)| json!({"id": k, "value": v}))
            .collect::<Vec<_>>(),
    });
    cfg.to_string()
}

// ---------------------------------------------------------------------------
// probe_fingerprint: real TLS fetch with the Chrome context + minimal HTTP/2
// ---------------------------------------------------------------------------

pub(crate) struct Url {
    pub(crate) host: String,
    pub(crate) path: String,
}

pub(crate) fn parse_url(url: &str) -> Result<Url, String> {
    let rest = url
        .strip_prefix("https://")
        .ok_or_else(|| "only https:// URLs are supported".to_string())?;
    let (host, path) = match rest.find('/') {
        Some(i) => (&rest[..i], &rest[i..]),
        None => (rest, "/"),
    };
    let host = host.split(':').next().unwrap_or(host).to_string();
    Ok(Url {
        host,
        path: path.to_string(),
    })
}

/// Establish a TLS connection with the Chrome-configured context (ALPN h2)
/// and apply the per-connection Chrome toggles. Shared by probe_fingerprint
/// and the h2 client.
pub fn connect_chrome_tls(host: &str) -> Result<SslStream<TcpStream>, String> {
    let connector = build_chrome_context().map_err(|e| e.to_string())?;
    let addr = format!("{}:443", host);
    let tcp = TcpStream::connect(&addr).map_err(|e| format!("tcp connect: {e}"))?;
    tcp.set_read_timeout(Some(std::time::Duration::from_secs(15)))
        .map_err(|e| e.to_string())?;
    tcp.set_write_timeout(Some(std::time::Duration::from_secs(15)))
        .map_err(|e| e.to_string())?;

    let mut config: ConnectConfiguration = connector.configure().map_err(|e| e.to_string())?;
    apply_per_connection_chrome_toggles(&config)?;
    let tls = config
        .connect(host, tcp)
        .map_err(|e| format!("tls handshake: {e}"))?;

    if let Some(alpn) = tls.ssl().selected_alpn_protocol() {
        if alpn != b"h2" {
            return Err(format!("server did not negotiate h2 (got {alpn:?})"));
        }
    } else {
        return Err("no ALPN negotiated".into());
    }
    Ok(tls)
}

/// Perform a real TLS fetch of `url` with the Chrome-configured context and
/// return (as JSON) whatever fingerprint data the endpoint echoes.
///
/// The request is sent over the Task-2 own HTTP/2 stack (h2 module): Chrome's
/// exact preface (SETTINGS + WINDOW_UPDATE), HPACK-encoded browser-order
/// headers. The endpoint response body is the JSON of e.g. tls.peet.ws/api/all.
pub fn probe_fingerprint(url: &str) -> Result<Value, String> {
    let body = crate::h2_fetch_bytes(url, "GET", &[])?;
    let json: Value =
        serde_json::from_slice(&body).map_err(|e| format!("bad json from endpoint: {e}"))?;
    Ok(extract_fingerprint_fields(json))
}

/// Project the full peet.ws payload onto the small set of fields the parity
/// tests consume, keeping the raw body under "raw".
fn extract_fingerprint_fields(full: Value) -> Value {
    // peet.ws nests the interesting values: tls.ja4 / tls.ja3_hash /
    // tls.extensions / http2.akamai_fingerprint. Fall back to top-level keys
    // for forward compatibility.
    let tls = full.get("tls").cloned().unwrap_or(Value::Null);
    let h2 = full.get("http2").cloned().unwrap_or(Value::Null);
    let get = |v: &Value, k: &str| v.get(k).cloned().unwrap_or(Value::Null);
    let mut out = json!({
        "ja4": get(&tls, "ja4"),
        "ja4_hash": get(&tls, "ja4_hash"),
        "ja3_hash": get(&tls, "ja3_hash"),
        "tls_extensions": get(&tls, "extensions"),
        "akamai_h2": get(&h2, "akamai_fingerprint"),
        "user_agent": get(&full, "user_agent"),
    });
    out["raw"] = full;
    out
}
